services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: a11y
      POSTGRES_PASSWORD: a11y
      #  POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
volumes:
  pgdata:
